
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/${dbName}?createDatabaseIfNotExist=true
    username: ${userName}
    password: ${password}
  mail:
    username: ${mailId}
    password: ${mailPassword}
  rabbitmq:    username: guest
    password: guest
    
twilio:
  account_sid: ${account_sid}
  auth_token: ${auth_token}
  trial_number: ${trial_number}
  
    
---
spring:
 profiles: prod
 
 
  
 
   