
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/${dbName}?createDatabaseIfNotExist=true
    username: ${userName}
    password: ${password}
  mail:
    username: ${mailId}
    password: ${mailPassword}
    
---
spring:
 profiles: prod
 
 
  
 
   